### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by caofei0806** [jasp-stats/jasp-desktop#2170]
JASP versions: 0.8.4-64-bit
OS name and version: Windows 10-64-bit
Hi,
This is the error I get:
I downloaded the latest JASP windows version from the official website, but the“runtime error” window always appears when I try to use the software. How to solve the problem.
![_20171116171754](https://user-images.githubusercontent.com/33741224/32928388-aa037a5a-cb8c-11e7-9bb2-8f16c5b805fc.png)

**Comment by fedoracoreuser** [comment]
Hello, this is the same problem we have in issue #2088 .

**Comment by FransMeerhoff** [comment]
Hi @caofei0806 

Thanks for your message. As mentioned by  fedoracoreuser some other people have this unclear problem too and made issue #2088 for it, so I would  like to  communicate on that issue and close this one. 

Some questions in advance for you:

- Do you have Visual Studio installed on your machine?
- Did you try the options mentioned in #2088?

If none of the work arounds will do, i hope that you can help us finding the 
cause of this problem, because we are not able to reproduce this problem on our site.

Kind regards 
Frans Meerhoff

**Comment by caofei0806** [comment]
This problem has been solved after installing Visual Studio,specifically, pertinent C++ programmes should be installed.

**Comment by FransMeerhoff** [comment]
HI @caofei0806 

Good to hear that your problem is solved!
But we are very curious to know what exactly happened here, because we do not understand that well, and we like to help other users who have similar problems.

- Did you already have Visual Studio installed on your machine or did you install an upgrade of it ?
- Which version of Visual Studio did you install?
- What do you mean by 'pertinent C++ programmes should be installed'? As far as we know this is not some special option of Visual Studio. Can you tell us more about this and why it was crucial for working / not working?

Thanks in advance.
Kind regards, Frans Meerhoff

**Comment by caofei0806** [comment]
1. I didn't install Visual Studio until I followed the tips you give here
2. I downloaded Visual Studio IDE from official website, the VS Community 2017 version. The installation interface informs that I should choose the workload and install components first, so I chose almost every component that reminds R. But the JASP still doesn't work.
3. Since the "runtime error" window says it is the "Microsoft Visual C++ runtime library" goes wrong, I  checked the VS installation interface and installed components related to C++.
![_20171122160119](https://user-images.githubusercontent.com/33741224/33116677-9998c8d8-cfa0-11e7-8aff-cab3590a5e22.jpg)
 The very option I chose is "universal tool platform for C++", as I have already marked a red line on the screen shot.
After that ,I restarted the computer and JASP run well
