### ISSUE TITLE
Plot loading and waiting indicators disappeared

### ISSUE THREAD

**Issue by quentingronau** [jasp-stats/jasp-desktop#798]
I rebased today (and also updated my R bundle) and now the loading/waiting indicators do not seem to work anymore.

**Comment by dropmann** [comment]
@quentingronau if you rebase again does it work then?

**Comment by quentingronau** [comment]
No, for the plots, it unfortunately still does not work.

**Comment by dropmann** [comment]
I have committed a fix for this.

**Comment by jonathon-love** [comment]
hey @dropmann,

so we have different loading indicators for the plots, than for the tables. i.e. the plots have a larger indicator in the center. where as now the plot status indicator is small like the tables.

**Comment by dropmann** [comment]
is it just the three non moving dots?

**Comment by quentingronau** [comment]
Hm, I rebased and still do not get the waiting/loading indicators for the plots. Do I need to copy some files manually?

**Comment by dropmann** [comment]
@jonathon-love  did the fix i committed work for you?

**Comment by jonathon-love** [comment]
worked for me, sounds like quentin might still be having issues.

hey @quentingronau,

> Do I need to copy some files manually?

shouldn't be any files you need to copy.

**Comment by dropmann** [comment]
@quentingronau will you be in tomorrow, as in friday? Can I have a look at it then?

**Comment by quentingronau** [comment]
No, sorry, I am flying to a conference tomorrow and will probably be back in Amsterdam at the beginning of August. If it works for other people it is probably not a big issue. I also still have the feeling it might be that I am doing something wrong.

**Comment by dropmann** [comment]
@quentingronau I'm equally, if not more, qualified to do stuff wrong, so i won't go betting on that horse just yet. Enjoy the conference.
